project_id = "kypftczqulebqlixfrij"

[functions.ai-marketing-tool]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.criativo-x-chat]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.send-proposal-email]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.whatsapp-queue-processor]
verify_jwt = false

[functions.whatsapp-followup-processor]
verify_jwt = false
